# Site settings
# title: "Acr Ev"
# description: "nome evento completo"
#url: "/" # the base hostname & protocol for your site
destination: ../site/
locale: "es"

# Site settings
title: "Estudiantes RSEF"
description: "Grupo de Estudiantes de la Real Sociedad Española de Física"
banner: img/banner.png
# url: "http://yourdomain.com" # the base hostname & protocol for your site
destination: ../site/
locale: "es"

# Build settings
markdown: kramdown
future: true
permalink: /blog/:year/:month/:day/:title/

#facebook
fb_admins:
fb_appid:

#Collections
collections:
  events:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
  persons:
    output: true
    permalink: /:categories/:title/

# gems:
#  - jekyll-redirect-from
#  - jekyll-sitemap
